apiVersion: skaffold/v2beta18
kind: Config
metadata:
    name: label-studio
build:
    artifacts:
        - image: asia.gcr.io/dhk-data-yoda-dev/label-studio
          docker:
              dockerfile: Dockerfile
deploy:
    kubectl:
        manifests:
            - ./deploy/skaffold/k8s/pod.yml
portForward:
    - resourceType: pod
      resourceName: label-studio-test
      port: 8080
